version: '3'
services:

  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: basededatospalabra
    ports:
      - "3306:3306"
    volumes:
      - ./database/basededatospalabra.sql:/docker-entrypoint-initdb.d/basededatospalabra.sql

  backend:
    build: ./backend
    depends_on:
      - database
    ports:
      - "8080:8080"